## **TITLE: LINEAR ALGEBRA**

### 1. Matrix Operation
Perform the following operations on the given matrices:
A=[[2    -1], [​0    3​]]
B=[[1   ​ 2], [-3      4​]]<br>
a. A+B<br>
b. AB<br>
c. 3A−2B

In [39]:
import numpy as np
import numpy.linalg as la

# Define two matrices
A = np.array([[2, -1],[0, 3]])
B = np.array([[1, 2],[-3, 4]])

In [40]:
# Compute addition between two matrices
print("The addition between matix A and matrix B:")
print(A + B)

# Compute the dot product using 'np.dot'
print("Dot product between matrices using 'np.dot':")
print(np.dot(A, B))

# Compute the dot product using @ operator
print("Dot product between matrices using '@' operator:")
print(A @ B)

# Compute '3A - 2B'
print("The substraction '3A - 2B':")
print((3 * A) - (2 * B ))


The addition between matix A and matrix B:
[[ 3  1]
 [-3  7]]
Dot product between matrices using 'np.dot':
[[ 5  0]
 [-9 12]]
Dot product between matrices using '@' operator:
[[ 5  0]
 [-9 12]]
The substraction '3A - 2B':
[[ 4 -7]
 [ 6  1]]


### 2. Determinants and Inverses  
Find the determinant of A.
Determine whether A is invertible. If yes, calculate A^-1.

In [41]:
# Computing determinant and inverse of matrix_a
deter_A = la.det(A)
inverse_A = la.inv(A)
print("The determinant of A is:",deter_A)

if deter_A != 0:
    print("The matrix is invertible (determinant != 0).")
    print("The inverse of A is:")
    print(inverse_A)

else:
    print("The matrix is not invertible.")


The determinant of A is: 6.0
The matrix is invertible (determinant != 0).
The inverse of A is:
[[0.5        0.16666667]
 [0.         0.33333333]]


### 3. Eigenvalues and Eigenvectors  
Compute the eigenvalues and eigenvectors of the matrix:
C=[[4    1], [​−2       1]​]

In [42]:
# Defining the matrix
C = np.array([[4, 1], [-2, 1]])

# Compute Eigenvalues and Eigenvectors
eigenvalues, eigenvectors = la.eig(C)

# Print the result
print("Marix C:")
print(C)
print("Eigenvalue:", eigenvalues)
print("Corresponding Eigenvector:\n", eigenvectors)

Marix C:
[[ 4  1]
 [-2  1]]
Eigenvalue: [3. 2.]
Corresponding Eigenvector:
 [[ 0.70710678 -0.4472136 ]
 [-0.70710678  0.89442719]]


### 4. You are given a dataset of cars with the following features:Number of cylinders (x1​)Engine size in liters (x2​)Horsepower (x3)
car 1:<br>
x1: 4<br>
x2:  1.5<br>
x3: 100<br>
and price: 20<br>

car 2:<br>
x1: 6<br>
x2:  2.0<br>
x3: 150<br>
and price: 30<br>

Then, find the price of a car 3 with features<br>
x1: 8<br>
x2:  3.0<br>
x3: 200<br>
price:?<br>


In [43]:
# Given data
X = np.array([[4, 1.5, 100],
              [6, 2.0, 150]])  # Features for Car 1 and Car 2

Y = np.array([20, 30])  # Prices for Car 1 and Car 2
beta = la.pinv(X) @ Y #using psudoinv for numerical stability
car3 = np.array([8, 3.0, 200]) #dataset for car3
car3_price = car3 @ beta #predicting price of car3 by doing dot product of car3 and beta
print("The price of car 3 is ", car3_price)


The price of car 3 is  40.00000000000006
